export const prod = [
        {id: "1", title: "Bermuda Clásica", size: "medium", color: "celeste", categoria: "Bermudas", description: "Bermuda de corte clasico", price: 1000, rating: 4.5, numReviews: 10, pictureUrl: "http://dl.dropboxusercontent.com/s/6730fjcza12z07z/bermudas.jpg", stock: 0},
        {id: "2", title: "Buzo Camperita Canguro", size: "large", color: "gris", categoria: "Buzos", description: "Camperita buzo con cierre y capucha", price: 2300, rating: 4.0, numReviews: 10, pictureUrl: "https://dl.dropboxusercontent.com/s/sznkrdei0997h5k/buzo.jpg", stock: 10},
        {id: "3", title: "Camisa Cuadrille", size: "XL", color: "marron", categoria: "Camisas", description: "Camisa cde corte clásico", price: 2000, rating: 4.5, numReviews: 10, pictureUrl: "https://dl.dropboxusercontent.com/s/mbucymp9ph75sk2/camisa.jpg", stock: 20},
        {id: "4", title: "Campera Inflada", size: "large", color: "negra", categoria: "Camperas", description: "Campera Inflada de corte recto", price: 2800, rating: 4.5, numReviews: 10, pictureUrl: "http://dl.dropboxusercontent.com/s/vohhuhmp9a3b6bo/campera.jpg", stock: 20},
        {id: "5", title: "Remera Básica", size: "small", color: "blanca", categoria: "Remeras", description: "Remera báscia cuello redondo", price: 800, rating: 4.5, numReviews: 10, pictureUrl: "http://dl.dropboxusercontent.com/s/lvnu9hqbtbargcr/remera.jpg", stock: 20},
        {id: "6", title: "Jean", size: "large", color: "azul", categoria: "Pantalones", description: "Jean recto de corte clásico", price: 2500, rating: 4.5, numReviews: 10, pictureUrl: "http://dl.dropboxusercontent.com/s/dk63kve5pbqv43i/denim.jpg", stock: 9},
        {id: "7", title: "Bermuda Cargo", size: "large", color: "beige", categoria: "Bermudas", description: "Bermuda cargo con detalles en bolsillos", price: 1000, rating: 4.5, numReviews: 10, pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_2X_894384-MLA44477092066_012021-F.webp/250x300", stock: 10},
        {id: "8", title: "Buzo Canguro", size: "medium", color: "blanco con mangas negras", categoria: "Buzos", description: "Buzon con capucha", price: 2300, rating: 4.5, numReviews: 10, pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_2X_801379-MLA40062848323_122019-F.webp/250x300", stock: 10},
        {id: "9", title: "Camisa Leñadora", size: "large", color: "roja y negrae", categoria: "Camisas", description: "Camisa leañadora de corte recto", price: 2000, rating: 4.5, numReviews: 10, pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_921347-MLA46360621032_062021-O.webp/250x300", stock: 20},
        {id: "10", title: "Campera Polo Clasica", size: "large", color: "verde oliva", categoria: "Camperas", description: "Campera Polo de gabardina de corte clásico", price: 2800, rating: 4.5, numReviews: 10, pictureUrl: "https://http2.mlstatic.com/D_945764-MLA31019783574_062019-O.jpg/250x300", stock: 20},
        {id: "11", title: "Remera Básica", size: "small", color: "negro", categoria: "Remeras", description: "Remera báscia cuello redondo", price: 800, rating: 4.5, numReviews: 10, pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_2X_616961-MLA44145300216_112020-F.webp/250x300", stock: 20},
        {id: "12", title: "Jean Elastizado", size: "large", color: "azul", categoria: "Pantalones", description: "Jean elastizado lavado", price: 2500, rating: 4.5, numReviews: 10, pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_804831-MLA42418408471_062020-O.webp/250x300", stock: 5},
    ]; 